<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'آیا از حذف این مورد مطمئن هستید؟',
    'Bra  Description' => 'توضیحات برند',
    'Bra  ID' => 'آیدی برند',
    'Bra  Im ID' => 'آیدی عکس برند',
    'Bra  Name' => 'نام برند',
    'Brands' => 'برندها',
    'Cat  ID' => 'آیدی دسته',
    'Cat  Name' => 'نام دسته',
    'Cat  Specification' => 'توضیحات دسته',
    'Cat Image ID' => 'آیدی عکس دسته',
    'Cat Parent ID' => 'آیدی والد دسته',
    'Categories' => 'دسته بندی ها',
    'Create' => 'ایجاد',
    'Create Brands' => 'ساخت برند جدید',
    'Create Category' => 'ساخت دسته بندی جدید',
    'Create Product' => 'ساخت محصول جدید',
    'Delete' => 'حذف',
    'Pro  Basket Count' => 'تعداد محصولات داخل سبد',
    'Pro  Bra ID' => 'آیدی محصول-برند',
    'Pro  Cat ID' => 'آیدی محصول-دسته',
    'Pro  Co ID' => 'آیدی نظرات محصول',
    'Pro  Code' => 'کد محصول',
    'Pro  Description' => 'توضیحات محصول',
    'Pro  Dislike Count' => 'تعداد پسند نشده محصول',
    'Pro  First Price' => 'قیمت اولیه محصول',
    'Pro  ID' => 'آیدی محصول',
    'Pro  Im ID' => 'آیدی عکس محصول',
    'Pro  Last Price' => 'آخرین قیمت محصول',
    'Pro  Like Count' => 'تعداد پسند شده محصول',
    'Pro  Name' => 'نام محصول',
    'Pro  Off Price' => 'قیمت تخفیف محصول',
    'Pro  Tag ID' => 'آیدی برچسب محصول',
    'Products' => 'محصولات',
    'Reset' => 'تنظیم مجدد',
    'Search' => 'جستجو',
    'Update' => 'بروز رسانی',
    'Update {modelClass}: ' => 'بروز رسانی',
    'Username' => 'نام کاربری',
];
