<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Bra  Description' => '',
    'Bra  ID' => '',
    'Bra  Im ID' => '',
    'Bra  Name' => '',
    'Brands' => '',
    'Cat  ID' => '',
    'Cat  Name' => '',
    'Cat  Specification' => '',
    'Cat Image ID' => '',
    'Cat Parent ID' => '',
    'Categories' => '',
    'Create' => '',
    'Create Brands' => '',
    'Create Category' => '',
    'Create Product' => '',
    'Delete' => '',
    'Pro  Basket Count' => '',
    'Pro  Bra ID' => '',
    'Pro  Cat ID' => '',
    'Pro  Co ID' => '',
    'Pro  Code' => '',
    'Pro  Description' => '',
    'Pro  Dislike Count' => '',
    'Pro  First Price' => '',
    'Pro  ID' => '',
    'Pro  Im ID' => '',
    'Pro  Last Price' => '',
    'Pro  Like Count' => '',
    'Pro  Name' => '',
    'Pro  Off Price' => '',
    'Pro  Tag ID' => '',
    'Products' => '',
    'Reset' => '',
    'Search' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
];
